package store

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"

	"wgpanel-api/internal/ipalloc"
)

var (
	ErrExternalRefTaken     = errors.New("external_ref already exists")
	ErrAccountNotFound      = errors.New("account not found")
	ErrNodeNotRegistered    = errors.New("node is not registered")
	ErrNodeCapacityExceeded = errors.New("node has no remaining capacity")
	ErrNoAvailableNode      = errors.New("no registered node has remaining capacity")
)

const ipHoldAfterDelete = 24 * time.Hour

type Account struct {
	ID             string
	ExternalRef    *string
	Label          string
	PublicKey      string
	DataQuotaBytes *int64
	DataUsedBytes  int64
	ExpiryAt       *time.Time
	DeviceLimit    *int
	// DeviceLimitHardEnforce upgrades device-limit detection to an automatic suspend
	// (PRD-account-management.md §6.4's per-account toggle); DeviceLimitExceededAt is
	// the standing "currently over the limit" flag, set/cleared by heartbeat ingest.
	DeviceLimitHardEnforce bool
	DeviceLimitExceededAt  *time.Time
	// BandwidthLimitMbps is enforced by the node agent via tc; nil = unshaped.
	BandwidthLimitMbps *int
	// SubscriptionToken is the capability for GET /api/v1/sub/{token} (migration 0016).
	SubscriptionToken string
	Status            string
	SuspendReason     *string
	IPReleaseAt       *time.Time
	OwnerKeyNamespace *string // the api_keys.key_id that created this account, or nil if created by an admin
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// AccountPeer is one (account, node) membership - an account can have a peer on
// several nodes simultaneously (see migration 0010). The account's WireGuard keypair
// itself lives on Account, not here - it's shared across every node this account has
// a peer on, since WireGuard peers are identified by public key and the same client
// key is valid as a peer on any number of independent servers at once.
//
// LastReceiveBytes/LastTransmitBytes (see migration 0011) are nil until this peer's
// first heartbeat observation - that first observation only seeds these columns, it
// never itself produces a traffic sample (see ingestBatchedTraffic's doc comment for
// why: without that distinction, the very first heartbeat after a peer starts being
// observed would attribute its entire lifetime WireGuard counter to one ~10s tick).
type AccountPeer struct {
	ID                string
	AccountID         string
	NodeID            string
	AssignedIP        string
	LastReceiveBytes  *int64
	LastTransmitBytes *int64
	LastHandshakeAt   *time.Time
	CreatedAt         time.Time
}

// AccountPeerWithNode adds the node identity fields wg-quick config generation needs
// (docs/STORY-09), fetched via ListAccountPeersWithNode's join.
type AccountPeerWithNode struct {
	AccountPeer
	NodeName           string
	NodePublicEndpoint string
	NodePublicKey      *string
}

const accountColumns = `id, external_ref, label, public_key, data_quota_bytes, data_used_bytes, expiry_at, device_limit, device_limit_hard_enforce, device_limit_exceeded_at, bandwidth_limit_mbps, subscription_token, status, suspend_reason, ip_release_at, owner_key_namespace, created_at, updated_at`

func scanAccount(row pgx.Row, a *Account) error {
	return row.Scan(
		&a.ID, &a.ExternalRef, &a.Label, &a.PublicKey,
		&a.DataQuotaBytes, &a.DataUsedBytes, &a.ExpiryAt, &a.DeviceLimit,
		&a.DeviceLimitHardEnforce, &a.DeviceLimitExceededAt, &a.BandwidthLimitMbps, &a.SubscriptionToken,
		&a.Status, &a.SuspendReason, &a.IPReleaseAt, &a.OwnerKeyNamespace, &a.CreatedAt, &a.UpdatedAt,
	)
}

// namespaceFilter is the SQL fragment scoping a query to $1 (the caller's namespace).
// $1 == nil means "admin - see everything," so the fragment becomes a no-op rather
// than an actual filter. Deliberately used everywhere an account id is looked up (not
// just list/search) so an API key can't act on another namespace's account even if
// it guesses a valid id - the row simply won't match, resulting in ErrAccountNotFound
// (404), never a separate "403 wrong namespace" that would leak the account's
// existence (PRD-telegram-bot-api.md §5.2).
const namespaceFilter = `($1::text IS NULL OR owner_key_namespace = $1)`

type CreateAccountParams struct {
	ExternalRef         *string
	Label               string
	NodeIDOrAuto        string // "" or "auto" = every eligible node; a real node UUID = pin to just that one
	PublicKey           string
	PrivateKeyEncrypted string
	DataQuotaBytes      *int64
	ExpiryAt            *time.Time
	DeviceLimit         *int
	BandwidthLimitMbps  *int
	SubscriptionToken   string   // generated by the handler (crypto/rand), never here
	OwnerKeyNamespace   *string  // nil when created by an admin
	AllowedNodeGroups   []string // nil/empty from an admin caller means "no restriction"; from an API key it's that key's node_groups
}

var ErrNodeGroupNotAllowed = errors.New("this API key is not allowed to provision accounts on that node's group")

type eligibleNode struct {
	id       string
	wgSubnet string
	capacity int
}

// CreateAccount inserts the account row, then gives it a WireGuard peer on every
// currently eligible node (status registered/online, node_group-restricted if the
// caller is a scoped API key) - or, if NodeIDOrAuto names a specific node, just that
// one. Node rows are locked in a deterministic order (ORDER BY id) so two concurrent
// fan-out creates can never deadlock against each other. A single full node is
// skipped, not fatal - only zero successfully provisioned nodes fails the whole
// call (see docs/STORY-09-multi-node-accounts.md).
func (s *Store) CreateAccount(ctx context.Context, p CreateAccountParams) (Account, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return Account{}, err
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op once committed

	restrictGroups := len(p.AllowedNodeGroups) > 0
	pinned := p.NodeIDOrAuto != "" && p.NodeIDOrAuto != "auto"

	var nodes []eligibleNode
	if pinned {
		var n eligibleNode
		var status, nodeGroup string
		err := tx.QueryRow(ctx, `
			SELECT id, wg_subnet, status, capacity_max_peers, node_group FROM nodes WHERE id = $1 FOR UPDATE
		`, p.NodeIDOrAuto).Scan(&n.id, &n.wgSubnet, &status, &n.capacity, &nodeGroup)
		if errors.Is(err, pgx.ErrNoRows) {
			return Account{}, ErrNodeNotFound
		}
		if err != nil {
			return Account{}, err
		}
		// "online" is what RecordHeartbeat overwrites status to the moment the
		// agent's first heartbeat lands after redeeming its join token - by then
		// the node has, by definition, already completed registration, so it's
		// an implicitly-registered superstate of "registered", not a rejection.
		if status != "registered" && status != "online" {
			return Account{}, ErrNodeNotRegistered
		}
		if restrictGroups && !contains(p.AllowedNodeGroups, nodeGroup) {
			return Account{}, ErrNodeGroupNotAllowed
		}
		nodes = append(nodes, n)
	} else {
		rows, err := tx.Query(ctx, `
			SELECT id, wg_subnet, capacity_max_peers
			FROM nodes
			WHERE status IN ('registered', 'online')
			  AND (NOT $1::bool OR node_group = ANY($2::text[]))
			ORDER BY id
			FOR UPDATE
		`, restrictGroups, p.AllowedNodeGroups)
		if err != nil {
			return Account{}, err
		}
		for rows.Next() {
			var n eligibleNode
			if err := rows.Scan(&n.id, &n.wgSubnet, &n.capacity); err != nil {
				rows.Close()
				return Account{}, err
			}
			nodes = append(nodes, n)
		}
		rows.Close()
		if err := rows.Err(); err != nil {
			return Account{}, err
		}
		if len(nodes) == 0 {
			return Account{}, ErrNoAvailableNode
		}
	}

	var a Account
	err = scanAccount(tx.QueryRow(ctx, `
		INSERT INTO accounts (external_ref, label, public_key, private_key_encrypted, data_quota_bytes, expiry_at, device_limit, bandwidth_limit_mbps, subscription_token, owner_key_namespace)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
		RETURNING `+accountColumns,
		p.ExternalRef, p.Label, p.PublicKey, p.PrivateKeyEncrypted, p.DataQuotaBytes, p.ExpiryAt, p.DeviceLimit, p.BandwidthLimitMbps, p.SubscriptionToken, p.OwnerKeyNamespace,
	), &a)
	if err != nil {
		if isUniqueViolation(err) {
			return Account{}, ErrExternalRefTaken
		}
		return Account{}, err
	}

	provisioned := 0
	for _, n := range nodes {
		ok, err := createPeerForNodeTx(ctx, tx, a.ID, n.id, n.wgSubnet, n.capacity)
		if err != nil {
			return Account{}, err
		}
		if ok {
			provisioned++
		}
	}
	if provisioned == 0 {
		if pinned {
			return Account{}, ErrNodeCapacityExceeded
		}
		return Account{}, ErrNoAvailableNode
	}

	if err := tx.Commit(ctx); err != nil {
		return Account{}, err
	}
	return a, nil
}

// createPeerForNodeTx allocates an IP and inserts one account_peers row for a single
// node, within an already-open transaction. Returns ok=false (not an error) if the
// node has no room - callers decide whether that's fatal (a single pinned node) or
// just means "skip this one, try the rest" (the fan-out case).
func createPeerForNodeTx(ctx context.Context, tx pgx.Tx, accountID, nodeID, wgSubnet string, capacity int) (bool, error) {
	var currentCount int
	if err := tx.QueryRow(ctx, `
		SELECT count(*) FROM account_peers ap
		JOIN accounts a ON a.id = ap.account_id
		WHERE ap.node_id = $1 AND a.status != 'deleted'
	`, nodeID).Scan(&currentCount); err != nil {
		return false, err
	}
	if currentCount >= capacity {
		return false, nil
	}

	rows, err := tx.Query(ctx, `
		SELECT ap.assigned_ip FROM account_peers ap
		JOIN accounts a ON a.id = ap.account_id
		WHERE ap.node_id = $1 AND (a.status != 'deleted' OR a.ip_release_at > now())
	`, nodeID)
	if err != nil {
		return false, err
	}
	var allocated []string
	for rows.Next() {
		var ip string
		if err := rows.Scan(&ip); err != nil {
			rows.Close()
			return false, err
		}
		allocated = append(allocated, ip)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return false, err
	}

	ip, err := ipalloc.NextFree(wgSubnet, allocated)
	if errors.Is(err, ipalloc.ErrSubnetExhausted) {
		return false, nil
	}
	if err != nil {
		return false, err
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO account_peers (account_id, node_id, assigned_ip) VALUES ($1, $2, $3)
	`, accountID, nodeID, ip); err != nil {
		return false, err
	}
	return true, nil
}

// BackfillAccountPeersForNode gives every currently-active account a peer on a node
// that just finished registration (called from RedeemJoinToken's success path) - so
// accounts provisioned before this node existed still end up synced to it, not just
// accounts created afterward. Unconditional across all active accounts regardless of
// which API key/admin originally created them or what node_groups restriction was
// applied at their creation time - node_group scoping restricts explicit node
// selection at creation, it isn't a standing partition promise for future nodes.
func (s *Store) BackfillAccountPeersForNode(ctx context.Context, nodeID string) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	var wgSubnet string
	var capacity int
	err = tx.QueryRow(ctx, `SELECT wg_subnet, capacity_max_peers FROM nodes WHERE id = $1 FOR UPDATE`, nodeID).Scan(&wgSubnet, &capacity)
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrNodeNotFound
	}
	if err != nil {
		return err
	}

	rows, err := tx.Query(ctx, `
		SELECT a.id FROM accounts a
		WHERE a.status = 'active'
		  AND NOT EXISTS (SELECT 1 FROM account_peers ap WHERE ap.account_id = a.id AND ap.node_id = $1)
	`, nodeID)
	if err != nil {
		return err
	}
	var accountIDs []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		accountIDs = append(accountIDs, id)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}

	for _, accountID := range accountIDs {
		if _, err := createPeerForNodeTx(ctx, tx, accountID, nodeID, wgSubnet, capacity); err != nil {
			return err
		}
	}

	return tx.Commit(ctx)
}

// ListAccountPeersWithNode returns every node this account currently has a peer on,
// joined with that node's public identity (needed for wg-quick config generation).
// Scoped to callerNamespace the same way GetAccount is - callers should already have
// 404'd via GetAccount before calling this, so a namespace mismatch here just yields
// an empty slice rather than needing its own not-found handling.
func (s *Store) ListAccountPeersWithNode(ctx context.Context, accountID string, callerNamespace *string) ([]AccountPeerWithNode, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT ap.id, ap.account_id, ap.node_id, ap.assigned_ip,
		       ap.last_receive_bytes, ap.last_transmit_bytes, ap.last_handshake_at, ap.created_at,
		       n.name, n.public_endpoint, n.public_key
		FROM account_peers ap
		JOIN nodes n ON n.id = ap.node_id
		JOIN accounts a ON a.id = ap.account_id
		WHERE ap.account_id = $2 AND `+namespaceFilter+`
		ORDER BY ap.created_at
	`, callerNamespace, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var peers []AccountPeerWithNode
	for rows.Next() {
		var p AccountPeerWithNode
		if err := rows.Scan(
			&p.ID, &p.AccountID, &p.NodeID, &p.AssignedIP,
			&p.LastReceiveBytes, &p.LastTransmitBytes, &p.LastHandshakeAt, &p.CreatedAt,
			&p.NodeName, &p.NodePublicEndpoint, &p.NodePublicKey,
		); err != nil {
			return nil, err
		}
		peers = append(peers, p)
	}
	return peers, rows.Err()
}

// DesiredPeer is what a node's WireGuard interface should have configured for one
// account - enough for cmd/agent to build a wgtypes.PeerConfig plus the tc traffic
// shaping (BandwidthLimitMbps, nil = unshaped) that rides along with it.
type DesiredPeer struct {
	PublicKey          string
	AssignedIP         string
	BandwidthLimitMbps *int
}

// ListDesiredPeersForNode is what handleAgentHeartbeat sends back to the agent every
// ~10s so it can reconcile the node's real WireGuard interface (docs/STORY-09-
// multi-node-accounts.md). Only 'active' accounts are included - suspending or
// deleting an account removes it from this list on the very next call, which is how
// enforcement actually happens: the agent's next ConfigureDevice simply stops
// including that peer, no separate "tear down" call needed anywhere.
func (s *Store) ListDesiredPeersForNode(ctx context.Context, nodeID string) ([]DesiredPeer, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT a.public_key, ap.assigned_ip, a.bandwidth_limit_mbps
		FROM account_peers ap
		JOIN accounts a ON a.id = ap.account_id
		WHERE ap.node_id = $1 AND a.status = 'active'
	`, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var peers []DesiredPeer
	for rows.Next() {
		var p DesiredPeer
		if err := rows.Scan(&p.PublicKey, &p.AssignedIP, &p.BandwidthLimitMbps); err != nil {
			return nil, err
		}
		peers = append(peers, p)
	}
	return peers, rows.Err()
}

// GetAccountBySubscriptionToken resolves a subscription capability URL's token to its
// account. Runs the same lazy expiry reconciliation as GetAccount so a subscription
// fetch can't hand out a config for an account that should already be suspended.
// Never namespace-scoped: possession of the token IS the authorization.
func (s *Store) GetAccountBySubscriptionToken(ctx context.Context, token string) (Account, error) {
	if err := s.reconcileExpiry(ctx); err != nil {
		return Account{}, err
	}
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx,
		`SELECT `+accountColumns+` FROM accounts WHERE subscription_token = $1 AND status != 'deleted'`,
		token,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

// RotateSubscriptionToken replaces the account's subscription token, immediately
// invalidating the old URL - the recovery path for a leaked/shared subscription link,
// deliberately independent of the WireGuard keypair (rotating the URL shouldn't force
// every legitimate device to re-import its tunnel config).
func (s *Store) RotateSubscriptionToken(ctx context.Context, id string, callerNamespace *string, newToken string) (Account, error) {
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx, `
		UPDATE accounts SET subscription_token = $3, updated_at = now()
		WHERE id = $2 AND status != 'deleted' AND `+namespaceFilter+`
		RETURNING `+accountColumns,
		callerNamespace, id, newToken,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

func contains(list []string, want string) bool {
	for _, v := range list {
		if v == want {
			return true
		}
	}
	return false
}

// reconcileExpiry flips any active account past its expiry_at to suspended. Run
// before every read (see GetAccount/ListAccounts) since there's no background
// scheduler yet - documented as a known limitation in STORY-03: an account nobody
// ever reads won't flip until someone does.
func (s *Store) reconcileExpiry(ctx context.Context) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE accounts SET status = 'suspended', suspend_reason = 'expired', updated_at = now()
		WHERE status = 'active' AND expiry_at IS NOT NULL AND expiry_at <= now()
	`)
	return err
}

// GetAccount looks up an account, scoped to callerNamespace (nil = admin, sees
// everything). A mismatched namespace and a genuinely missing id are indistinguishable
// on purpose - both return ErrAccountNotFound.
func (s *Store) GetAccount(ctx context.Context, id string, callerNamespace *string) (Account, error) {
	if err := s.reconcileExpiry(ctx); err != nil {
		return Account{}, err
	}
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx,
		`SELECT `+accountColumns+` FROM accounts WHERE id = $2 AND `+namespaceFilter,
		callerNamespace, id,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

func (s *Store) ListAccounts(ctx context.Context, limit int, callerNamespace *string) ([]Account, error) {
	if err := s.reconcileExpiry(ctx); err != nil {
		return nil, err
	}
	rows, err := s.pool.Query(ctx,
		`SELECT `+accountColumns+` FROM accounts WHERE status != 'deleted' AND `+namespaceFilter+` ORDER BY created_at LIMIT $2`,
		callerNamespace, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var accounts []Account
	for rows.Next() {
		var a Account
		if err := scanAccount(rows, &a); err != nil {
			return nil, err
		}
		accounts = append(accounts, a)
	}
	return accounts, rows.Err()
}

type UpdateAccountParams struct {
	Label          *string
	DataQuotaBytes *int64
	ExpiryAt       *time.Time
	DeviceLimit    *int
	// BandwidthLimitMbps follows the same nil-means-unchanged convention, with one
	// extension: 0 explicitly clears the limit back to NULL (unshaped). "Remove the
	// rate limit" is a real operation in a way "remove the quota" hasn't needed to be,
	// and 0 Mbps is meaningless as an actual limit, so the sentinel is unambiguous.
	BandwidthLimitMbps     *int
	DeviceLimitHardEnforce *bool
}

// UpdateAccount only touches fields explicitly provided (nil = leave unchanged).
func (s *Store) UpdateAccount(ctx context.Context, id string, callerNamespace *string, p UpdateAccountParams) (Account, error) {
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx, `
		UPDATE accounts SET
			label = COALESCE($3, label),
			data_quota_bytes = COALESCE($4, data_quota_bytes),
			expiry_at = COALESCE($5, expiry_at),
			device_limit = COALESCE($6, device_limit),
			bandwidth_limit_mbps = CASE WHEN $7::int IS NULL THEN bandwidth_limit_mbps
			                            WHEN $7 = 0 THEN NULL
			                            ELSE $7 END,
			device_limit_hard_enforce = COALESCE($8, device_limit_hard_enforce),
			updated_at = now()
		WHERE id = $2 AND status != 'deleted' AND `+namespaceFilter+`
		RETURNING `+accountColumns,
		callerNamespace, id, p.Label, p.DataQuotaBytes, p.ExpiryAt, p.DeviceLimit, p.BandwidthLimitMbps, p.DeviceLimitHardEnforce,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

func (s *Store) SuspendAccount(ctx context.Context, id string, callerNamespace *string, reason string) (Account, error) {
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx, `
		UPDATE accounts SET status = 'suspended', suspend_reason = $3, updated_at = now()
		WHERE id = $2 AND status != 'deleted' AND `+namespaceFilter+`
		RETURNING `+accountColumns,
		callerNamespace, id, reason,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

func (s *Store) EnableAccount(ctx context.Context, id string, callerNamespace *string) (Account, error) {
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx, `
		UPDATE accounts SET status = 'active', suspend_reason = NULL, updated_at = now()
		WHERE id = $2 AND status != 'deleted' AND `+namespaceFilter+`
		RETURNING `+accountColumns,
		callerNamespace, id,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

// RenewAccount adds quota and/or extends expiry, then reactivates the account if it
// was suspended solely for quota_exceeded or expired and the new numbers resolve
// that (PRD §6.2-6.3). A manual or abuse_flag suspension is left untouched - renewing
// quota doesn't override an operator's deliberate suspension.
func (s *Store) RenewAccount(ctx context.Context, id string, callerNamespace *string, addQuotaBytes *int64, extendExpiryTo *time.Time) (Account, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return Account{}, err
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	var a Account
	err = scanAccount(tx.QueryRow(ctx, `
		UPDATE accounts SET
			data_quota_bytes = CASE WHEN $3::bigint IS NULL THEN data_quota_bytes
			                        WHEN data_quota_bytes IS NULL THEN NULL
			                        ELSE data_quota_bytes + $3::bigint END,
			expiry_at = COALESCE($4, expiry_at),
			updated_at = now()
		WHERE id = $2 AND status != 'deleted' AND `+namespaceFilter+`
		RETURNING `+accountColumns,
		callerNamespace, id, addQuotaBytes, extendExpiryTo,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	if err != nil {
		return Account{}, err
	}

	quotaResolved := a.SuspendReason != nil && *a.SuspendReason == "quota_exceeded" &&
		(a.DataQuotaBytes == nil || a.DataUsedBytes < *a.DataQuotaBytes)
	expiryResolved := a.SuspendReason != nil && *a.SuspendReason == "expired" &&
		(a.ExpiryAt == nil || a.ExpiryAt.After(time.Now()))

	if a.Status == "suspended" && (quotaResolved || expiryResolved) {
		err = scanAccount(tx.QueryRow(ctx, `
			UPDATE accounts SET status = 'active', suspend_reason = NULL, updated_at = now()
			WHERE id = $1
			RETURNING `+accountColumns,
			id,
		), &a)
		if err != nil {
			return Account{}, err
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return Account{}, err
	}
	return a, nil
}

// SoftDeleteAccount marks the account deleted and starts the 24h IP-reuse hold
// (PRD §6.1) rather than releasing the IP immediately. account_peers rows are left
// in place (not deleted) - every query that computes capacity/allocation/desired
// heartbeat peers already filters on the account's status, so a deleted account's
// peer rows are simply inert rather than needing their own cleanup pass.
func (s *Store) SoftDeleteAccount(ctx context.Context, id string, callerNamespace *string) (Account, error) {
	var a Account
	err := scanAccount(s.pool.QueryRow(ctx, `
		UPDATE accounts SET status = 'deleted', ip_release_at = now() + $3, updated_at = now()
		WHERE id = $2 AND status != 'deleted' AND `+namespaceFilter+`
		RETURNING `+accountColumns,
		callerNamespace, id, ipHoldAfterDelete,
	), &a)
	if errors.Is(err, pgx.ErrNoRows) {
		return Account{}, ErrAccountNotFound
	}
	return a, err
}

// GetAccountPrivateKey fetches only the encrypted private key - kept separate from
// the general Account struct/scanAccount so ordinary reads never carry key material
// through code paths that don't need it.
func (s *Store) GetAccountPrivateKey(ctx context.Context, id string, callerNamespace *string) (string, error) {
	var encrypted string
	err := s.pool.QueryRow(ctx,
		`SELECT private_key_encrypted FROM accounts WHERE id = $2 AND `+namespaceFilter,
		callerNamespace, id,
	).Scan(&encrypted)
	if errors.Is(err, pgx.ErrNoRows) {
		return "", ErrAccountNotFound
	}
	return encrypted, err
}
